api.AMLayerKind = {
    AnySheet: 0,
    PixelSheet: 1,
    AdjustmentSheet: 2,
    TextSheet: 3,
    VectorSheet: 4,
    SmartObjectSheet: 5,
    VideoSheet: 6,
    LayerGroupSheet: 7,
    ThreeDSheet: 8,
    GradientSheet: 9,
    PatternSheet: 10,
    SolidColorSheet: 11,
    BackgroundSheet: 12,
    HiddenSectionBounder: 13,
};
